name: "Setup"
description: "Setup environment"

runs:
  using: "composite"
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install Node.js 26.x
      uses: actions/setup-node@v6
      with:
        node-version: "26.x"

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm@latest-11

    - name: Install node modules
      shell: bash
      run: pnpm install

    - name: Get pnpm store path
      id: pnpm-cache-dir
      shell: bash
      run: echo "dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        path: |
          ${{ steps.pnpm-cache-dir.outputs.dir }}
          ./node_modules
