name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Type check
        run: nix develop --command npm run tc

      - name: Lint
        run: nix develop --command npm run lint

      - name: Test
        run: nix develop --command npm run test
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: nix develop --command npm run prepublishOnly

      - name: List npm config
        run: nix develop --command npm config list

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          access: public

      - name: Tag release
        run: |
          #!/bin/bash
          set -eux

          NAME="$(node -p "require('./package.json').author.name")"
          if [[ -z "${NAME}" ]]; then
            echo "author.name is not set in package.json"
            exit 1
          fi

          EMAIL="$(node -p "require('./package.json').author.email")"
          if [[ -z "${EMAIL}" ]]; then
            echo "author.email is not set in package.json"
            exit 1
          fi

          VERSION="$(node -p "require('./package.json').version")"
          if [[ -z "${VERSION}" ]]; then
            echo "version is not set in package.json"
            exit 1
          fi

          git fetch --tags
          if git tag | grep "${VERSION}"; then
            echo "'${VERSION}' already exists. No action taken."
            exit 0
          fi

          git config --global user.email "${EMAIL}"
          git config --global user.name "${NAME}"
          git tag -a "${VERSION}" -m "Release ${VERSION}"
          git push --follow-tags
