name: CI

on:
  push:
    branches-ignore:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Type check
        run: nix develop --command npm run tc

      - name: Lint
        run: nix develop --command npm run lint

      - name: Test
        run: nix develop --command npm run test
